/*
 * @Description:
 * @Author: zhuoda
 * @Date: 2021-08-12 18:07:31
 * @LastEditTime: 2021-09-01
 * @LastEditors: zhuoda
 */
/**
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface EmployeeVo {
  /**
   * 主键id
   */
  employeeId: number;
  /**
   * 登录账号
   */
  loginName?: string;
  /**
   * 性别
   */
  gender?: number;
  /**
   * 员工名称
   */
  actualName?: string;
  /**
   * 手机号码
   */
  phone?: string;
  /**
   * 部门id
   */
  departmentId?: number;

  departmentName?: string
  /**
   * 是否被禁用
   */
  disabledFlag?: boolean;

  /**
   * 是否超管
   */
  administratorFlag?: boolean;
  /**
   * 创建时间
   */
  createTime?: string;

  /**
   * 角色列表
   */
  roleIdList?: Array<string>;

  /**
   * 角色名称列表
   */
  roleNameList?: Array<string>;


}
