/*
 * @Description:
 * @Author: zhuoda
 * @Date: 2021-08-12 18:07:31
 * @LastEditTime: 2021-09-01
 * @LastEditors: zhuoda
 */
/**
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DepartmentSimpleVo } from '/@/api/system/department/model/department-simple-vo';

export interface EmployeeVo {
  /**
   * 员工名称
   */
  actualName?: string;
  /**
   * 出生日期
   */
  birthday?: string;
  /**
   * 创建时间
   */
  createTime?: string;
  /**
   * 部门
   */
  department?: Array<DepartmentSimpleVo>;
  /**
   * 部门id
   */
  departmentId?: string;
  /**
   * 是否被禁用
   */
  disabledFlag?: boolean;
  /**
   * 邮箱
   */
  email?: string;
  /**
   * 主键id
   */
  id: number;
  /**
   * 身份证
   */
  idCard?: string;
  /**
   * 是否离职
   */
  leaveFlag?: boolean;
  /**
   * 登录账号
   */
  loginName?: string;
  /**
   * 别名
   */
  nickName?: string;
  /**
   * 手机号码
   */
  phone?: string;
}
