/*
 * @Author: zhuoda
 * @Date: 2021-08-14 16:52:13
 * @LastEditTime: 2021-08-14 16:53:58
 * @LastEditors: zhuoda
 * @Description: 
 * @FilePath: /smart-admin/src/api/system/employee/model/employee-query-dto.ts
 */
/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PageParamModel } from "/@/api/base-model/page-param-model";

export interface EmployeeQueryDto extends PageParamModel{ 
    /**
     * 部门id
     */
    departmentId?: number;
    /**
     * 是否禁用
     */
    disabledFlag?: boolean;
    /**
     * 员工id集合
     */
    employeeIdList?: Array<number>;
    /**
     * 搜索词
     */
    keyword?: string;
    /**
     * 是否查询总条数
     */
    searchCount?: boolean;
}

