/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HomeWaitHandleVo { 
    /**
     * 驳回完成收款单数
     */
    rejectCompleteReceiveOrderNum?: number;
    /**
     * 驳回收款单数
     */
    rejectReceiveOrderNum?: number;
    /**
     * 驳回退款单数
     */
    rejectRefundOrderNum?: number;
    /**
     * 签订合同数
     */
    signContractNum?: number;
    /**
     * 关联线索欠款（余额）总金额
     */
    userTotalAmount?: number;
    /**
     * 待跟进数量
     */
    waitTrackNum?: number;
}

