/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HomeEmployeeReceiveVo } from './home-employee-receive-vo';
import { HomeEmployeeOrderVo } from './home-employee-order-vo';
import { HomeEmployeeSaleTargetVo } from './home-employee-sale-target-vo';


export interface HomeAmountStatisticsVo { 
    orderVO?: HomeEmployeeOrderVo;
    receiveVO?: HomeEmployeeReceiveVo;
    saleTargetVO?: HomeEmployeeSaleTargetVo;
}

