import {DepartmentCreateDto} from "/@/api/system/department/model/department-create-dto";

/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DepartmentUpdateDto extends DepartmentCreateDto{
    /**
     * 部门id
     */
    departmentId?: number;
}

