/*
 * @Author: zhuoda
 * @Date: 2021-08-12 18:51:32
 * @LastEditTime: 2021-09-01
 * @LastEditors: zhuoda
 * @Description:
 * @FilePath: /smart-admin/src/api/system/department/model/department-vo.ts
 */
/**
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DepartmentVo {
  /**
   * 部门id
   */
  departmentId: number;
  /**
   * 部门负责人id
   */
  managerId?: number;
  /**
   * 部门负责人姓名
   */
  managerName?: string;
  /**
   * 部门名称
   */
  name: string;
  /**
   * 父级部门id
   */
  parentId?: number;
  /**
   * 排序
   */
  sort?: number;
}
