/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataScopeViewTypeVo } from './data-scope-view-type-vo';


export interface DataScopeAndViewTypeVo { 
    /**
     * 数据范围类型
     */
    dataScopeType?: number;
    /**
     * 描述
     */
    dataScopeTypeDesc?: string;
    /**
     * 数据范围名称
     */
    dataScopeTypeName?: string;
    /**
     * 顺序
     */
    dataScopeTypeSort?: number;
    /**
     * 可见范围列表
     */
    viewTypeList?: Array<DataScopeViewTypeVo>;
}

