/*
 * @Author: zhuoda
 * @Date: 2021-08-30 11:10:09
 * @LastEditTime: 2021-08-30 11:20:04
 * @LastEditors: zhuoda
 * @Description:
 * @FilePath: /smart-admin/src/api/system/role/model/role-query-dto.ts
 */
/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageParamModel} from "/@/api/base-model/page-param-model";


export interface RoleQueryDto  extends PageParamModel {
    /**
     * 角色id
     */
    roleId?: number;
    /**
     * 关键字
     */
    keywords?: string;
}

