/*
 * @Author: zhuoda
 * @Date: 2021-08-28 14:19:22
 * @LastEditTime: 2021-08-28 15:08:02
 * @LastEditors: zhuoda
 * @Description:
 * @FilePath: /smart-admin/src/api/system/menu/model/menu-simple-tree-vo.ts
 */
/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MenuSimpleTreeVo {
  /**
   * 子菜单
   */
  children?: Array<MenuSimpleTreeVo>;
  /**
   * 功能点关联菜单ID
   */
  contextMenuId?: number;
  /**
   * 菜单ID
   */
  menuId?: number;
  /**
   * 父菜单ID
   */
  parentId?: number;
  /**
   * 菜单类型
   */
  menuType?:number;
  /**
   * 菜单名称
   */
  menuName?: string;
}
