/*
 * @Description:
 * @Author: zhuoda
 * @Date: 2021-08-10
 * @LastEditTime: 2021-09-01 21:16:00
 * @LastEditors: zhuoda
 */
/**
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MenuTreeVo {
  /**
   * 是否缓存
   */
  cacheFlag?: boolean;
  /**
   * 菜单子集
   */
  children?: Array<MenuTreeVo>;
  /**
   * 组件路径
   */
  component?: string;
  /**
   * 功能点关联菜单ID
   */
  contextMenuId?: number;
  /**
   * 创建时间
   */
  createTime?: string;
  /**
   * 创建人
   */
  createUserId?: number;
  /**
   * 禁用状态
   */
  disabledFlag?: boolean;
  /**
   * 是否为外链
   */
  frameFlag?: boolean;
  /**
   * 菜单图标
   */
  icon?: string;
  /**
   * 菜单ID
   */
  menuId: number;
  /**
   * 菜单名称
   */
  menuName?: string;
  /**
   * 类型:  <br>  export const <br> MENU_TYPE_ENUM = <BR> {<br>&nbsp;&nbsp;CATALOG:{<br>&nbsp;&nbsp;&nbsp;&nbsp;value:1,<br>&nbsp;&nbsp;&nbsp;&nbsp;desc:\'目录\'<br>&nbsp;&nbsp;},<br>&nbsp;&nbsp;MENU:{<br>&nbsp;&nbsp;&nbsp;&nbsp;value:2,<br>&nbsp;&nbsp;&nbsp;&nbsp;desc:\'菜单\'<br>&nbsp;&nbsp;},<br>&nbsp;&nbsp;POINTS:{<br>&nbsp;&nbsp;&nbsp;&nbsp;value:3,<br>&nbsp;&nbsp;&nbsp;&nbsp;desc:\'功能点\'<br>&nbsp;&nbsp;}<br>} <br>
   */
  menuType: number;
  /**
   * 父菜单ID 无上级可传0
   */
  parentId?: number;
  /**
   * 路由地址
   */
  path?: string;
  /**
   * 接口权限
   */
  perms?: string;
  /**
   * 接口权限
   */
  permsList?: string[];
  /**
   * 显示顺序
   */
  sort?: number;
  /**
   * 更新时间
   */
  updateTime?: string;
  /**
   * 更新人
   */
  updateUserId?: number;
  /**
   * 显示状态
   */
  visibleFlag?: boolean;
}
