/*
 * @Author: zhuoda
 * @Date: 2021-08-28 14:19:33
 * @LastEditTime: 2021-08-28 14:19:46
 * @LastEditors: zhuoda
 * @Description: 
 * @FilePath: /smart-admin/src/api/system/role-menu/modal/role-menu-tree-vo.ts
 */
/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MenuSimpleTreeVo } from "../../menu/model/menu-simple-tree-vo";


export interface RoleMenuTreeVo { 
    /**
     * 菜单列表
     */
    menuTreeList?: Array<MenuSimpleTreeVo>;
    /**
     * 角色ID
     */
    roleId?: number;
    /**
     * 选中的菜单ID
     */
    selectedMenuId?: Array<number>;
}

