/*
 * @Description:
 * @Author: zhuoda
 * @Date: 2021-08-12 18:19:34
 * @LastEditTime: 2021-09-01
 * @LastEditors: zhuoda
 */
/**
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DepartmentSimpleVo {
  /**
   * 部门id
   */
  id: number;
  /**
   * 部门名称
   */
  name: string;
  /**
   * 部门简称
   */
  shortName?: string;
}
