/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DepartmentCreateDto {
    /**
     * 部门负责人id
     */
    managerId?: number;
    /**
     * 部门名称
     */
    name?: string;
    /**
     * 排序
     */
    sort?: number;
    /**
     * 上级部门id (可选)
     */
    parentId?: number;
}

