/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataScopeViewTypeVo { 
    /**
     * 可见范围
     */
    viewType?: number;
    /**
     * 级别,用于表示范围大小
     */
    viewTypeLevel?: number;
    /**
     * 可见范围名称
     */
    viewTypeName?: string;
}

