/*
 * @Author: zhuoda
 * @Date: 2021-08-30 11:10:09
 * @LastEditTime: 2021-08-30 11:20:04
 * @LastEditors: zhuoda
 * @Description: 
 * @FilePath: /smart-admin/src/api/system/role/model/role-query-dto.ts
 */
/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortItemDto } from './sort-item-dto';


export interface RoleQueryDto { 
    /**
     * 页码(不能为空)
     */
    pageNum: number;
    /**
     * 每页数量(不能为空)
     */
    pageSize: number;
    /**
     * 角色id
     */
    roleId?: number;
    /**
     * 角色名称
     */
    roleName?: string;
    /**
     * 是否查询总条数
     */
    searchCount?: boolean;
    /**
     * 排序字段集合
     */
    sortItemList?: Array<SortItemDto>;
}

