/**
 * smart-admin-local
 * http://localhost:50110/v2/api-docs?group=Admin
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleUpdateDto {
    /**
     * 角色id
     */
    roleId?: number;
    /**
     * 角色描述
     */
    remark?: string;
    /**
     * 角色名称
     */
    roleName?: string;
}

